# admin_bot/states.py

(
    ADMIN_GRANT_INPUT,
    ADMIN_REVOKE_INPUT,
    ADMIN_EXTEND_USER,
    ADMIN_EXTEND_PICK,
    ADMIN_EXTEND_CUSTOM_DAYS,
    ADMIN_BROADCAST_MSG,
    ADMIN_EDIT_RULES,
    ADMIN_EDIT_SUPPORT,
) = range(8)
